# --------------------------------------------------------------------
#
# !\file makefile
# !\brief Makefile for building the project.
# !\author Colin J.D. Stewart
#
# --------------------------------------------------------------------
#             Copyright (c) 2026. Colin J.D. Stewart
#                     All rights reserved
# --------------------------------------------------------------------

#
# DO NOT EDIT THIS FILE. FOR CUSTOMISATION, SEE makefile.project.mk
#
ifeq (,$(wildcard makefile.project.mk))
  $(error Missing makefile.project.mk (project settings file))
endif
include makefile.project.mk
-include makefile.local.mk

# -----------------------------------
# Directory layout
# -----------------------------------
SRC_DIR := src
BIN_DIR := $(SRC_DIR)/bin
LIB_DIR := $(SRC_DIR)/lib
INC_DIR := $(SRC_DIR)/inc
OBJ_DIR := $(SRC_DIR)/bld
OUT_DIR := bld

TST_DIR := $(SRC_DIR)/tst
TST_UT_DIR := $(TST_DIR)/ut
TST_SY_DIR := $(TST_DIR)/sy
TST_OBJ_DIR := $(TST_DIR)/bld

# -----------------------------------
# Dependency include scanning (dep/*)
# -----------------------------------
DEP_ROOT := dep
DEP_MAP_DIR := $(OBJ_DIR)/depinc
DEP_NAMES := $(shell [ -d "$(DEP_ROOT)" ] && find "$(DEP_ROOT)" -mindepth 1 -maxdepth 1 -type d -exec basename {} \; || true)
DEP_INC_DIRS := $(wildcard $(DEP_ROOT)/*/src/inc)
DEP_INC_FLAGS := $(foreach dir,$(DEP_INC_DIRS),-I$(dir))

# -----------------------------------
# Toolchain
# -----------------------------------
CXX ?= g++
AR  ?= ar

# MODE and CXX_STD may be set in makefile.project.mk
MODE ?= debug
CXX_STD ?= c++20


# -----------------------------------
# Flags and options
# -----------------------------------
CPPFLAGS += -I$(INC_DIR) $(DEP_INC_FLAGS) -I$(DEP_MAP_DIR) -MMD -MP
CXXFLAGS += -std=$(CXX_STD) -Wall -Wextra -Wpedantic
LDFLAGS +=
LDLIBS +=

ifeq ($(MODE),release)
  CXXFLAGS += -O2 -DNDEBUG
else
  CXXFLAGS += -O0 -g
endif

# Project hooks
CPPFLAGS += $(USER_CPPFLAGS) -I$(DEP_MAP_DIR)
CXXFLAGS += $(USER_CXXFLAGS)
LDFLAGS += $(USER_LDFLAGS)
LDLIBS += $(USER_LDLIBS)

# -----------------------------------
# Output artefacts
# -----------------------------------
EXEC_OUT   := $(OUT_DIR)/$(BIN_NAME)
STATIC_OUT := $(OUT_DIR)/lib$(LIB_BASENAME).a
SHARED_OUT := $(OUT_DIR)/lib$(LIB_BASENAME).so

BUILD_TARGETS :=

ifeq ($(BUILD_EXE),1)
  BUILD_TARGETS += exe
endif

ifeq ($(BUILD_STATIC),1)
  BUILD_TARGETS += static
endif

ifeq ($(BUILD_SHARED),1)
  BUILD_TARGETS += shared
endif

ifeq ($(strip $(BUILD_TARGETS)),)
  $(warning No build targets enabled (BUILD_EXE/STATIC/SHARED all 0))
endif


# -----------------------------------
# Source discovery
# -----------------------------------

BIN_SOURCES := $(wildcard $(BIN_DIR)/*.cpp)

LIB_CPP_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.cpp' || true)
LIB_C_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.c' || true)
LIB_S_SOURCES := $(shell [ -d "$(LIB_DIR)" ] && find "$(LIB_DIR)" -type f -name '*.S' || true)

# ------------------------------------
# Object file lists
# ------------------------------------

LIB_SOURCES := $(LIB_CPP_SOURCES) $(LIB_C_SOURCES) $(LIB_S_SOURCES)
BIN_OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(BIN_SOURCES))
LIB_CPP_OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.o,$(LIB_CPP_SOURCES))
LIB_C_OBJECTS := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.o,$(LIB_C_SOURCES))
LIB_CPP_PIC_OBJECTS := $(patsubst $(SRC_DIR)/%.cpp,$(OBJ_DIR)/%.pic.o,$(LIB_CPP_SOURCES))
LIB_C_PIC_OBJECTS := $(patsubst $(SRC_DIR)/%.c,$(OBJ_DIR)/%.pic.o,$(LIB_C_SOURCES))

LIB_OBJECTS := $(LIB_CPP_OBJECTS) $(LIB_C_OBJECTS)
LIB_PIC_OBJECTS := $(LIB_CPP_PIC_OBJECTS) $(LIB_C_PIC_OBJECTS)
ALL_OBJECTS := $(BIN_OBJECTS) $(LIB_OBJECTS) $(LIB_PIC_OBJECTS)


# -----------------------------------
# Verbose mode
# -----------------------------------
VERBOSE ?= 0
ifeq ($(VERBOSE),1)
  Q :=
else
  Q := @
endif

# -----------------------------------
# Compilation rules
# -----------------------------------

# C++ sources in src/bin (no PIC)
$(OBJ_DIR)/bin/%.o: $(BIN_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (bin): $<"
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C++ sources in src/lib
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (lib): $<"
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C sources in src/lib
$(OBJ_DIR)/lib/%.o: $(LIB_DIR)/%.c
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C (lib): $<"
	$(CXX) $(CPPFLAGS) -x c -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C++ sources in src/lib compiled with PIC for shared library target
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.cpp
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C++ (lib,pic): $<"
	$(CXX) $(CPPFLAGS) $(CXXFLAGS) -fPIC -MT $@ -MF $(@:.o=.d) -c $< -o $@

# C sources in src/lib compiled with PIC for shared library target
$(OBJ_DIR)/lib/%.pic.o: $(LIB_DIR)/%.c
	$(Q)mkdir -p $(dir $@)
	$(Q)echo "C (lib,pic): $<"
	$(CXX) $(CPPFLAGS) -fPIC -x c -MT $@ -MF $(@:.o=.d) -c $< -o $@



# -----------------------------------
# Output directory
# -----------------------------------
$(OUT_DIR):
	$(Q)mkdir -p $(OUT_DIR)

# -----------------------------------
# Executable
# -----------------------------------
.DEFAULT_GOAL := all

all: dep-incmap $(BUILD_TARGETS)

exe: dep-incmap $(EXEC_OUT)

$(EXEC_OUT): $(BIN_OBJECTS) $(LIB_OBJECTS) | $(OUT_DIR)
	$(Q)echo "Link (exe): $@"
	$(Q)$(CXX) $(LDFLAGS) -o $@ $^ $(LDLIBS)

# -----------------------------------
# Static library
# -----------------------------------
static: dep-incmap $(STATIC_OUT)

$(STATIC_OUT): $(LIB_OBJECTS) | $(OUT_DIR)
	$(Q)echo "Archive (static): $@"
	$(Q)rm -f $@
	$(Q)$(AR) rcs $@ $^

# -----------------------------------
# Shared library
# -----------------------------------
shared: dep-incmap $(SHARED_OUT)

$(SHARED_OUT): $(LIB_PIC_OBJECTS) | $(OUT_DIR)
	$(Q)echo "Link (shared): $@"
	$(Q)$(CXX) -shared $(LDFLAGS) -o $@ $^ $(LDLIBS)



# -----------------------------------
# Auto dependencies
# -----------------------------------
DEPS := $(ALL_OBJECTS:.o=.d)
-include $(DEPS)



# -----------------------------------
# PHONY targets
# -----------------------------------
.PHONY: help
help:
	@echo "Targets:"
	@echo "  all        Build enabled targets (BUILD_EXE/STATIC/SHARED)"
	@echo "  exe        Build executable"
	@echo "  static     Build static library"
	@echo "  shared     Build shared library"
	@echo "  tests      Run unit + system tests (if present)"
	@echo "  ut         Run unit tests"
	@echo "  sy         Run system tests"
	@echo "  clean      Remove build artefacts"
	@echo "  distclean  Same as clean"
	@echo ""
	@echo "Options:"
	@echo "  MODE=debug|release"
	@echo "  VERBOSE=1"


.PHONY: dep-incmap
dep-incmap:
	$(Q)mkdir -p "$(DEP_MAP_DIR)"
	$(Q)for d in $(DEP_NAMES); do \
		if [ -d "$(DEP_ROOT)/$$d/src/inc/$$d" ]; then \
			ln -sfn "../../$(DEP_ROOT)/$$d/src/inc/$$d" "$(DEP_MAP_DIR)/$$d"; \
		elif [ -d "$(DEP_ROOT)/$$d/src/inc" ]; then \
			ln -sfn "../../$(DEP_ROOT)/$$d/src/inc" "$(DEP_MAP_DIR)/$$d"; \
		fi; \
	done

.PHONY: ut
ut:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" all; \
		$(MAKE) -C "$(TST_UT_DIR)" run; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

.PHONY: sy
sy: all
	@if [ -x "$(TST_SY_DIR)/runner" ]; then \
		"$(TST_SY_DIR)/runner"; \
	else \
		echo "No system test runner found at $(TST_SY_DIR)/runner"; \
	fi

.PHONY: tests
tests: ut sy

.PHONY: clean clean-tests clean-all distclean

clean-all:
	$(Q)echo "Cleaning build artefacts..."
	$(Q)for d in "$(OBJ_DIR)" "$(TST_OBJ_DIR)" "$(OUT_DIR)"; do \
		mkdir -p "$$d"; \
		find "$$d" -mindepth 1 \( -type f -o -type l \) ! -name ".gitignore" -delete; \
		find "$$d" -mindepth 1 -type d -empty -delete; \
	done

clean-tests:
	@if [ -f "$(TST_UT_DIR)/Makefile" ] || [ -f "$(TST_UT_DIR)/makefile" ]; then \
		$(MAKE) -C "$(TST_UT_DIR)" clean; \
	else \
		echo "No unit test Makefile found in $(TST_UT_DIR)"; \
	fi

clean: clean-all clean-tests

distclean: clean

.PHONY: all exe static shared tests ut sy dep-incmap clean clean-all clean-tests distclean
